# # [build]
# #   functions = "functions-build"
# #   command = "npm run build"
# #   publish = "functions-build"

# # [[redirects]]
# #   from = "/*"
# #   to = "/.netlify/functions/server"
# #   status = 200

# [functions]
#   external_node_modules = ["express"]
#   node_bundler = "esbuild"
# [[redirects]]
#   force = true
#   from = "/server/*"
#   status = 200
#   to = "/.netlify/functions/server/:splat"

